load("@rules_cc//cc:defs.bzl", "cc_library")

exports_files([
        "memory_layout.h",
    ])

cc_library(
    name = "memory_layout",
    hdrs = [
        "memory_layout.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)
